package net.au7.journalApp.service;

import net.au7.journalApp.entity.User;
import net.au7.journalApp.repository.UserRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class UserDetailServiceImplTests {

    @Autowired
    private UserDetailServiceImpl userDetailService;

    @MockitoBean
    private UserRepository userRepository;

    @Test
    public void userDetailServiceImplTest() {
        // Create entity using constructor generated by Lombok (@NonNull)
        User userEntity = new User("Ram", "123456789");

        // Mock repository behavior
        when(userRepository.findByUsername(anyString())).thenReturn(userEntity);

        // Call the service method
        UserDetails user = userDetailService.loadUserByUsername("Ram");

        // Verify behavior and assertions
        assertNotNull(user);
        assertEquals("Ram", user.getUsername());
        verify(userRepository, times(1)).findByUsername("Ram");
    }
}